spring.application.name=qldv-api
server.port=8085
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${ORACLE_URL}
spring.datasource.username=${ORACLE_USERNAME}
spring.datasource.password=${ORACLE_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

logging.level.org.springframework.web=DEBUG

qldv.app.id=${QLDV_APP_ID}
jwt.secret.key=${JWT_SECRET_KEY}
jwt.expiration=${EXPIRATION_MS}

iam.api.url=${IAM_API_URL}
iam.api.key=${IAM_API_KEY}

qldv.database.url=${QLDV_DB_URL}
qldv.database.api_key=${QLDV_DB_API_KEY}
qldv.system.url=${QLDV_SYSTEM_URL}
qldv.app.api.key=${APP_API_KEY}

app.service.publicKeyPath=${PUBLIC_KEY_PATH}
app.service.privateKeyPath=${PRIVATE_KEY_PATH}
