spring.application.name=qldv-api
server.port=8085
spring.config.import=optional:file:.env[.properties]

logging.level.org.springframework.web=DEBUG
# Disable datasource and JPA auto-configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration

qldv.app.id=${QLDV_APP_ID}
jwt.secret.key=${JWT_SECRET_KEY}
jwt.expiration=${EXPIRATION_MS}

iam.api.url=${IAM_API_URL}
iam.api.key=${IAM_API_KEY}

qldv.database.url=${QLDV_DB_URL}
qldv.database.api_key=${QLDV_DB_API_KEY}
qldv.system.url=${QLDV_SYSTEM_URL}

app.service.publicKeyPath=${PUBLIC_KEY_PATH}
app.max.rows.export=${MAX_ROWS_EXPORT}
app.max.rows.pdf.export=${MAX_ROWS_PDF_EXPORT}
# CORS configuration
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:8085,http://localhost:3000}

#Folder zip file
zip.folder.path=${ZIP_FOLDER_PATH}
zip.folder.day.threshould=${DAYS_THRESHOLD}

export.pdf.service.url=${TRANSFORM_PDF_SERVICE_URL}

#Storage
s3.endpoint=${S3_ENDPOINT}
s3.bucket-name=${S3_BUCKET_NAME}
s3.project-prefix=${S3_PROJECT_PREFIX}
s3.access-key=${S3_ACCESS_KEY}
s3.secret-key=${S3_SECRET_KEY}

attachment.max-size=${ATTACHMENT_MAX_SIZE:102400}
